webservice_home:
    pattern:  /home
    defaults: { _controller: EpsWebServiceBundle:Default:home }
    requirements:
        _method:  GET
        _format: JSON
webservice_slider:
    pattern:  /slider
    defaults: { _controller: EpsWebServiceBundle:Default:slider }
    requirements:
        _method:  GET
        _format: JSON