<?php

namespace Eps\StaticPagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SliderPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderPhotoRepository extends EntityRepository
{
}