imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @EpsUserBundle/Resources/config/services.xml }


framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true
    validation: { enable_annotations: true }

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - "::forms.html.twig"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    read_from: "%kernel.root_dir%/../www"
    use_controller: false
    bundles:        [ ]
    filters:
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  sendmail

# FOS User Bundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Eps\UserBundle\Entity\User
    from_email:
        address:        alfo.agonia@gmail.com
        sender_name:    Efrei Picture Studio (EPS)
    profile:
        form:
            type: eps_user_profile
    registration:
        form:
            type: eps_user_registration
        confirmation:
            enabled:    true

# Services Configuration
services:
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

# OneUp Uploader Configuration
oneup_uploader:
    mappings:
        reporter: 
            frontend: dropzone
            allowed_extensions:    ['jpg', 'jpeg','png', 'gif', 'JPG', 'JPEG', 'PNG', 'GIF']
            allowed_mimetypes:     ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']
            namer: upload.custom_namer
            #storage:
            #    type: filesystem
            #    directory: %kernel.root_dir%/../web/test2
        video: 
            frontend: dropzone
            allowed_extensions:    ['mp4', 'mpeg', 'mpg', 'avi', 'MP4', 'MPEG', 'MPG', 'AVI']
            allowed_mimetypes:     ['video/mp4', 'video/mpeg', 'video/mpg', 'video/avi']
            namer: upload.custom_namer
            #storage:
            #    type: filesystem
            #    directory: %kernel.root_dir%/../web/test2
        slider: 
            frontend: dropzone
            allowed_extensions:    ['jpg', 'jpeg','png', 'gif', 'JPG', 'JPEG', 'PNG', 'GIF']
            allowed_mimetypes:     ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']
            namer: upload.custom_namer
            #storage:
            #    type: filesystem
            #    directory: %kernel.root_dir%/../web/test2