
# EPS Routes
EpsStaticPagesBundle:
    resource: "@EpsStaticPagesBundle/Resources/config/routing.yml"
    prefix:   /

EpsAdminBundle:
    resource: "@EpsAdminBundle/Resources/config/routing.yml"
    prefix:   /

EpsUserBundle:
    resource: "@EpsUserBundle/Resources/config/routing.yml"
    prefix:   /

EpsVideoBundle:
    resource: "@EpsVideoBundle/Resources/config/routing.yml"
    prefix:   /

EpsPhotoBundle:
    resource: "@EpsPhotoBundle/Resources/config/routing.yml"
    prefix:   /

EpsHomepageBundle:
    resource: "@EpsHomepageBundle/Resources/config/routing.yml"
    prefix:   /

# FOS User Bundle Routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# OneUp Uploader Routes
oneup_uploader:
    resource: .
    type: uploader