<?php

namespace Eps\PhotoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
	public function findAllByYearAndCategoryC($year, $cat, $start = 0, $limit = 50)
	{
		$emConfig = $this->getEntityManager()->getConfiguration();
		$emConfig->addCustomDatetimeFunction('YEAR', 'DoctrineExtensions\Query\Mysql\Year');

		$query = $this->createQueryBuilder('a');

		$parameters = array();
		if($year != 'all' 	&& $year != NULL) { $query->where('YEAR(a.date) = :year'); $parameters['year'] = $year; }
		if($cat  != 'all' 	&& $cat  != NULL) { $query->andWhere('a.category = :cat'); $parameters['cat'] = $cat; }

		$query->setParameters($parameters);
					
		$query = $query->orderBy('a.id', 'DESC')
					->setMaxResults($limit)
					->join('a.category', 'c')
					->join('a.reporters', 'r')
					->addSelect('c')
					->addSelect('r')
					->getQuery();
        return $query->getResult();
	}

	public function findYears()
	{
		$emConfig = $this->getEntityManager()->getConfiguration();
		$emConfig->addCustomDatetimeFunction('YEAR', 'DoctrineExtensions\Query\Mysql\Year');

		$qb = $this->createQueryBuilder('a');
		$qb->select('DISTINCT YEAR(a.date) AS years')->orderBy('years', 'DESC');

		$results = $qb->getQuery()->getResult();
		$years = array();
		if($results != NULL)
			foreach($results as $result)
				$years[] = $result['years'];
		return $years;
	}
}