<?php

namespace Eps\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findReporters()
	{
		/*$qb = $this->createQueryBuilder('u');
		$qb->select('DISTINCT u.pseudo AS pseudo')->where('u.role CONTAINS("ROLE_USER")');

		$results = $qb->getQuery()->getResult();
		$years = array();
		if($results != NULL)
			foreach($results as $result)
				$years[] = $result['years'];
		return $years;*/
	}
}