admin:
    pattern:  /admininistration
    defaults: { _controller: EpsAdminBundle:Default:index }


# Static pages
admin_static:
    pattern:  /admin/static
    defaults: { _controller: EpsAdminBundle:Static:index }

admin_static_create:
    pattern:  /admin/static/new
    defaults: { _controller: EpsAdminBundle:Static:create }

admin_static_delete:
    pattern:  /admin/static/delete/{id}
    defaults: { _controller: EpsAdminBundle:Static:delete }

admin_static_edit:
    pattern:  /admin/static/edit/{id}
    defaults: { _controller: EpsAdminBundle:Static:edit }