admin_album:
    pattern:  /
    defaults: { _controller: "EpsPhotoBundle:Album:index" }

admin_carousel:
    pattern:  /carousel/
    defaults: { _controller: "EpsPhotoBundle:Album:carousel" }

admin_carousel_edit:
    pattern:  /carousel/{id}/edit
    defaults: { _controller: "EpsPhotoBundle:Album:carouselEdit" }

admin_carousel_update:
    pattern:  /carousel/{id}/update
    defaults: { _controller: "EpsPhotoBundle:Album:carouselUpdate" }
    requirements: { _method: post|put }

admin_carousel_new:
    pattern:  /carousel/new
    defaults: { _controller: "EpsPhotoBundle:Album:carouselNew" }

admin_carousel_create:
    pattern:  /carousel/create
    defaults: { _controller: "EpsPhotoBundle:Album:carouselCreate" }

admin_carousel_upload:
    pattern:  /carousel/{id}/upload
    defaults: { _controller: "EpsPhotoBundle:Album:carouselUpload" }

admin_carousel_delete:
    pattern:  /carousel/{id}/delete
    defaults: { _controller: "EpsPhotoBundle:Album:carouselDelete" }

admin_album_paginated:
    pattern: /page/{page}
    defaults: { _controller: EpsPhotoBundle:Album:index }

admin_album_show:
    pattern:  /{id}/show
    defaults: { _controller: "EpsPhotoBundle:Album:show" }

admin_album_new:
    pattern:  /new
    defaults: { _controller: "EpsPhotoBundle:Album:new" }

admin_album_new_upload:
    pattern: /new/upload/{year}/{id}
    defaults: { _controller: EpsPhotoBundle:Album:newUpload }

admin_album_new_thumb:
    pattern: /new/thumb/{year}/{id}
    defaults: { _controller: EpsPhotoBundle:Album:newThumb }

admin_album_new_finish:
    pattern: /new/finish/{year}/{id}
    defaults: { _controller: EpsPhotoBundle:Album:newFinish }

admin_album_create:
    pattern:  /create
    defaults: { _controller: "EpsPhotoBundle:Album:create" }
    requirements: { _method: post }

admin_album_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EpsPhotoBundle:Album:edit" }

admin_album_add_upload:
    pattern:  /{id}/upload
    defaults: { _controller: "EpsPhotoBundle:Album:addUpload" }

admin_album_remove_upload:
    pattern:  /{id}/uploadEdit
    defaults: { _controller: "EpsPhotoBundle:Album:removeUpload" }
    requirements: { _method: post|put }

admin_album_update:
    pattern:  /{id}/update
    defaults: { _controller: "EpsPhotoBundle:Album:update" }
    requirements: { _method: post|put }

admin_album_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EpsPhotoBundle:Album:delete" }

admin_album_publish:
    pattern:  /{id}/publish
    defaults: { _controller: "EpsPhotoBundle:Album:publish" }
